dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: Do+xBHwednLl1CXws3r1MViKW5Q0CkaXKGX4TTdlZXAaXZQf5NjMAjKmEfOfeS/YHVGAt3HW44zZK+Y7Kb2brAc2cYqwLe7cWHpKoxFVUbLjcQ3Pgfj/RaUfdlyC4It2iiyOuAjL/aVm2XCKyJDblw1ZxeHz8/o/csfvrvZF596wn1/ek7JUWNGvNyxhp8ewQz0vn6Xf5tuJEyr5gd9gVhS14OkcoxSa3UDd8zwNr7i+8AB4IVu1oRsyeruMvrCtHY5Ijs/pUpL6O1CnYhdkkB0vhDmhnGgoW19pSvnoWdMoVBnUDhiaX+dfNyJR62noBv3iQ0jGwD3yGY1Pdv9moAWP0kxhvVzta7zrMIWpRhhLo7hTDnGVPK7yCqQg6iA0YQg64Hte23l9pYMUVW/sDteKqp2wIcwi7p6Z8c/M5yIFNR8BnvtLrS8+0EIu2/oQ2YJueBTNPWykpqFkpEYvvPJ61OenPB0ktPlZNclGBfWLRBq0RbFNAcaXw2l7t9dOXs61xq0+QEnGU8Jjvvmy/YQ7Niu83WmIH2lTFpuH5IuUXpRw/rdZdpO6q7NdgCx3Jl2uKmQ4qUhDHx+n2TVORRgfQbMU8gV7FMzRGgZVpg6VWZjN6GXmehNT0K133Ns+hEDFQH4ic6mxHwO10Y3+OMhaYxJ3g7VSFXNlAPN8PRw=
