FROM alpine:3.9

# Update and install base packages
RUN apk update && apk upgrade \
&& apk add curl wget bash \
&& apk add curl-dev ruby-dev build-base \
&& apk add ruby ruby-io-console ruby-bundler

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292
ENV APP_HOME /app

WORKDIR ${APP_HOME}
COPY . ${APP_HOME}/
RUN bundle install

CMD ["puma"]