global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#max_mayorovskiy'
