version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USER_NAME}/ui:${VERSION_IMAGE}
    ports:
      - 9292:${PUBLIC_PORT}/tcp
    networks:
      front_net:
        aliases:
          - ui

  post:
    image: ${USER_NAME}/post:${VERSION_IMAGE}
    networks:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post

  comment:
    image: ${USER_NAME}/comment:${VERSION_IMAGE}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment

volumes:
  post_db:

networks:
  front_net:
      driver: bridge
      ipam:
        config:
          - subnet: 10.0.4.0/24
  back_net:
      driver: bridge
      ipam:
        config:
          - subnet: 10.0.3.0/24
