version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    image: ${USER_NAME}/ui:${VERSION_IMAGE}
    ports:
      - 9292:${PUBLIC_PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USER_NAME}/post:${VERSION_IMAGE}
    networks:
      - front_net
      - back_net

  comment:
    image: ${USER_NAME}/comment:${VERSION_IMAGE}
    networks:
      - front_net
      - back_net
    links:
      - "post_db:comment_db"

  prometheus:
    image: ${USER_NAME}/prometheus
    networks:
      - front_net
      - back_net
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

  node-exporter:
    image: prom/node-exporter:v0.15.2
    networks:
      - front_net
      - back_net
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  mongodb_exporter:
    image: mongodb-exporter:master
    environment:
    - MONGODB_URI=mongodb://post_db:27017
    networks:
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
      driver: bridge
      ipam:
        config:
          - subnet: 10.0.4.0/24
  back_net:
      driver: bridge
      ipam:
        config:
          - subnet: 10.0.3.0/24
