kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: yVaGFl+qlIErV8HFk7SLlWJ4a2nrD71qONHLT63ZkPs=
      - identity: {}
